gTrickHouse_Mechadoll_Oddish:: @ 27ECBC
	.string "Floramon$"

gTrickHouse_Mechadoll_Poochyena:: @ 27ECC3
	.string "Dracmon$"

gTrickHouse_Mechadoll_Taillow:: @ 27ECCD
	.string "Hawkmon$"

gTrickHouse_Mechadoll_Azurill:: @ 27ECD5
	.string "Moonmon$"

gTrickHouse_Mechadoll_Lotad:: @ 27ECDD
	.string "Otamamon$"

gTrickHouse_Mechadoll_Wingull:: @ 27ECE3
	.string "Falcomon$"

gTrickHouse_Mechadoll_Dustox:: @ 27ECEB
	.string "Stingmon$"

gTrickHouse_Mechadoll_Zubat:: @ 27ECF2
	.string "DemiDevimn$"

gTrickHouse_Mechadoll_Nincada:: @ 27ECF8
	.string "Kunemon$"

gTrickHouse_Mechadoll_Ralts:: @ 27ED00
	.string "Puttimon$"

gTrickHouse_Mechadoll_Zigzagoon:: @ 27ED06
	.string "Kudamon$"

gTrickHouse_Mechadoll_Slakoth:: @ 27ED10
	.string "Gazimon$"

gTrickHouse_Mechadoll_Poochyena2:: @ 27ED18
	.string "Dracmon$"

gTrickHouse_Mechadoll_Shroomish:: @ 27ED22
	.string "Kotemon$"

gTrickHouse_Mechadoll_Zigzagoon2:: @ 27ED2C
	.string "Kudamon$"

gTrickHouse_Mechadoll_Poochyena3:: @ 27ED36
	.string "Dracmon$"

gTrickHouse_Mechadoll_Zubat2:: @ 27ED40
	.string "DemiDevimon$"

gTrickHouse_Mechadoll_Carvanha:: @ 27ED46
	.string "Tylomon$"

gTrickHouse_Mechadoll_BurnHeal:: @ 27ED4F
	.string "Burn Heal$"

gTrickHouse_Mechadoll_HarborMail:: @ 27ED59
	.string "Harbor Mail$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "They will cost more.$"

gTrickHouse_Mechadoll_CostLess::
	.string "They will cost less.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Same price$"

gTrickHouse_Mechadoll_Male::
	.string "Male$"

gTrickHouse_Mechadoll_Female::
	.string "Female$"

gTrickHouse_Mechadoll_Neither::
	.string "Neither$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Elderly men$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Elderly ladies$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Same number$"

gTrickHouse_Mechadoll_None::
	.string "None$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
